export { discoverUrisFromPlatform } from '../common/uris/platform/index.js'
export type { PlatformHandler, PlatformMethodOptions } from '../common/uris/platform/types.js'
export { defaultPlatformOptions } from '../feeds/defaults.js'
export { blogspotHandler } from '../feeds/platform/handlers/blogspot.js'
export { blueskyHandler } from '../feeds/platform/handlers/bluesky.js'
export { githubHandler } from '../feeds/platform/handlers/github.js'
export { gitlabHandler } from '../feeds/platform/handlers/gitlab.js'
export { kickstarterHandler } from '../feeds/platform/handlers/kickstarter.js'
export { redditHandler } from '../feeds/platform/handlers/reddit.js'
export { substackHandler } from '../feeds/platform/handlers/substack.js'
export { tumblrHandler } from '../feeds/platform/handlers/tumblr.js'
export { wordpressHandler } from '../feeds/platform/handlers/wordpress.js'
export { youtubeHandler } from '../feeds/platform/handlers/youtube.js'
