name: Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Check feeds
        run: bun check/feeds.ts

      - name: Check favicons
        run: bun check/favicons.ts
