name: Checkup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  checkup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Check links
        run: bun checkup/check.ts
